language: go
dist: trusty
go:
  - 1.8.x
  - master

install:
  - go get -v github.com/Masterminds/glide 
  - make get-deps
  - go get -u github.com/golang/lint/golint

script:
  - make test
  - make build
  - golint .
